In [43]:
import pandas as pd
import numpy as np

In [44]:
df = pd.read_csv('spamhamdata.csv',sep='\t', header=None, names=['class', 'text'])
df.head()

,class,text
0,ham,"Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives around here though"

In [45]:
text = df['text']
classe = df['class']
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords

In [46]:
import gensim
model = gensim.models.word2vec.Word2Vec.load("Word2Vec-local.bin")

In [47]:
b = model.wv.vectors
b.shape

(3570, 100)

In [48]:
sentences = df['text']
lemmatizer = WordNetLemmatizer()
import re
corpus = []
for i in range(len(sentences)):
    review = re.sub('[^a-zA-Z]', ' ', sentences[i])
    review = review.lower()
    review = review.split()
    review = [lemmatizer.lemmatize(word) for word in review ]
    review = ' '.join(review)
    corpus.append(review)

In [49]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [50]:
words = []
for sent in corpus:
    sent_tokenized = sent_tokenize(sent)
    for sent in sent_tokenized:
        words.append(simple_preprocess(sent))
        print(simple_preprocess(sent))

['go', 'until', 'jurong', 'point', 'crazy', 'available', 'only', 'in', 'bugis', 'great', 'world', 'la', 'buffet', 'cine', 'there', 'got', 'amore', 'wat']
['ok', 'lar', 'joking', 'wif', 'oni']
['free', 'entry', 'in', 'wkly', 'comp', 'to', 'win', 'fa', 'cup', 'final', 'tkts', 'st', 'may', 'text', 'fa', 'to', 'to', 'receive', 'entry', 'question', 'std', 'txt', 'rate', 'apply', 'over']
['dun', 'say', 'so', 'early', 'hor', 'already', 'then', 'say']
['nah', 'don', 'think', 'he', 'go', 'to', 'usf', 'he', 'life', 'around', 'here', 'though']
['freemsg', 'hey', 'there', 'darling', 'it', 'been', 'week', 'now', 'and', 'no', 'word', 'back', 'like', 'some', 'fun', 'you', 'up', 'for', 'it', 'still', 'tb', 'ok', 'xxx', 'std', 'chgs', 'to', 'send', 'to', 'rcv']
['even', 'my', 'brother', 'is', 'not', 'like', 'to', 'speak', 'with', 'me', 'they', 'treat', 'me', 'like', 'aid', 'patent']
['per', 'your', 'request', 'melle', 'melle', 'oru', 'minnaminunginte', 'nurungu', 'vettam', 'ha', 'been', 'set', 'your', 'callertune', 'for', 'all', 'caller', 'press', 'to', 'copy', 'your', 'friend', 'callertune']
['winner', 'valued', 'network', 'customer', 'you', 'have', 'been', 'selected', 'to', 'receivea', 'prize', 'reward', 'to', 'claim', 'call', 'claim', 'code', 'kl', 'valid', 'hour', 'only']
['had', 'your', 'mobile', 'month', 'or', 'more', 'entitled', 'to', 'update', 'to', 'the', 'latest', 'colour', 'mobile', 'with', 'camera', 'for', 'free', 'call', 'the', 'mobile', 'update', 'co', 'free', 'on']
['gonna', 'be', 'home', 'soon', 'and', 'don', 'want', 'to', 'talk', 'about', 'this', 'stuff', 'anymore', 'tonight', 've', 'cried', 'enough', 'today']
['six', 'chance', 'to', 'win', 'cash', 'from', 'to', 'pound', 'txt', 'csh', 'and', 'send', 'to', 'cost', 'day', 'day', 'tsandcs', 'apply', 'reply', 'hl', 'info']
['urgent', 'you', 'have', 'won', 'week', 'free', 'membership', 'in', 'our', 'prize', 'jackpot', 'txt', 'the', 'word', 'claim', 'to', 'no', 'www', 'dbuk', 'net', 'lccltd', 'pobox', 'ldnw', 'rw']
['ve', 'been', 'searching', 'for', 'the', 'right', 'word', 'to', 'thank', 'you', 'for', 'this', 'breather', 'promise', 'wont', 'take', 'your', 'help', 'for', 'granted', 'and', 'will', 'fulfil', 'my', 'promise', 'you', 'have', 'been', 'wonderful', 'and', 'blessing', 'at', 'all', 'time']
['have', 'date', 'on', 'sunday', 'with', 'will']
['to', 'use', 'your', 'credit', 'click', 'the', 'wap', 'link', 'in', 'the', 'next', 'txt', 'message', 'or', 'click', 'here', 'http', 'wap', 'com', 'qjkgighjjgcbl']
['oh', 'watching', 'here']
['eh', 'remember', 'how', 'spell', 'his', 'name', 'yes', 'did', 'he', 'naughty', 'make', 'until', 'wet']
['fine', 'if', 'that', 'the', 'way', 'feel', 'that', 'the', 'way', 'it', 'gota']
['england', 'macedonia', 'dont', 'miss', 'the', 'goal', 'team', 'news', 'txt', 'ur', 'national', 'team', 'to', 'eg', 'england', 'to', 'try', 'wale', 'scotland', 'txt', 'poboxox', 'wq']
['is', 'that', 'seriously', 'how', 'you', 'spell', 'his', 'name']
['going', 'to', 'try', 'for', 'month', 'ha', 'ha', 'only', 'joking']
['so', 'pay', 'first', 'lar', 'then', 'when', 'is', 'da', 'stock', 'comin']
['aft', 'finish', 'my', 'lunch', 'then', 'go', 'str', 'down', 'lor', 'ard', 'smth', 'lor', 'finish', 'ur', 'lunch', 'already']
['ffffffffff', 'alright', 'no', 'way', 'can', 'meet', 'up', 'with', 'you', 'sooner']
['just', 'forced', 'myself', 'to', 'eat', 'slice', 'really', 'not', 'hungry', 'tho', 'this', 'suck', 'mark', 'is', 'getting', 'worried', 'he', 'know', 'sick', 'when', 'turn', 'down', 'pizza', 'lol']
['lol', 'your', 'always', 'so', 'convincing']
['did', 'you', 'catch', 'the', 'bus', 'are', 'you', 'frying', 'an', 'egg', 'did', 'you', 'make', 'tea', 'are', 'you', 'eating', 'your', 'mom', 'left', 'over', 'dinner', 'do', 'you', 'feel', 'my', 'love']
['back', 'amp', 'we', 're', 'packing', 'the', 'car', 'now', 'll', 'let', 'you', 'know', 'if', 'there', 'room']
['ahhh', 'work', 'vaguely', 'remember', 'that', 'what', 'doe', 'it', 'feel', 'like', 'lol']
['wait', 'that', 'still', 'not', 'all', 'that', 'clear', 'were', 'you', 'not', 'sure', 'about', 'me', 'being', 'sarcastic', 'or', 'that', 'that', 'why', 'doesn', 'want', 'to', 'live', 'with']
['yeah', 'he', 'got', 'in', 'at', 'and', 'wa', 'apologetic', 'had', 'fallen', 'out', 'and', 'she', 'wa', 'actin', 'like', 'spoilt', 'child', 'and', 'he', 'got', 'caught', 'up', 'in', 'that', 'till', 'but', 'we', 'won', 'go', 'there', 'not', 'doing', 'too', 'badly', 'cheer', 'you']
['tell', 'me', 'anything', 'about', 'you']
['for', 'fear', 'of', 'fainting', 'with', 'the', 'of', 'all', 'that', 'housework', 'you', 'just', 'did', 'quick', 'have', 'cuppa']
['thanks', 'for', 'your', 'subscription', 'to', 'ringtone', 'uk', 'your', 'mobile', 'will', 'be', 'charged', 'month', 'please', 'confirm', 'by', 'replying', 'yes', 'or', 'no', 'if', 'you', 'reply', 'no', 'you', 'will', 'not', 'be', 'charged']
['yup', 'ok', 'go', 'home', 'look', 'at', 'the', 'timing', 'then', 'msg', 'again', 'xuhui', 'going', 'to', 'learn', 'on', 'nd', 'may', 'too', 'but', 'her', 'lesson', 'is', 'at', 'am']
['oops', 'll', 'let', 'you', 'know', 'when', 'my', 'roommate', 'done']
['see', 'the', 'letter', 'on', 'my', 'car']
['anything', 'lor', 'decide']
['hello', 'how', 'you', 'and', 'how', 'did', 'saturday', 'go', 'wa', 'just', 'texting', 'to', 'see', 'if', 'you', 'decided', 'to', 'do', 'anything', 'tomo', 'not', 'that', 'trying', 'to', 'invite', 'myself', 'or', 'anything']
['pls', 'go', 'ahead', 'with', 'watt', 'just', 'wanted', 'to', 'be', 'sure', 'do', 'have', 'great', 'weekend', 'abiola']
['did', 'forget', 'to', 'tell', 'you', 'want', 'you', 'need', 'you', 'crave', 'you', 'but', 'most', 'of', 'all', 'love', 'you', 'my', 'sweet', 'arabian', 'steed', 'mmmmmm', 'yummy']
['rodger', 'burn', 'msg', 'we', 'tried', 'to', 'call', 'you', 're', 'your', 'reply', 'to', 'our', 'sm', 'for', 'free', 'nokia', 'mobile', 'free', 'camcorder', 'please', 'call', 'now', 'for', 'delivery', 'tomorrow']
['who', 'are', 'you', 'seeing']
['great', 'hope', 'you', 'like', 'your', 'man', 'well', 'endowed', 'am', 'lt', 'gt', 'inch']
['no', 'call', 'message', 'missed', 'call']
['didn', 'you', 'get', 'hep', 'immunisation', 'in', 'nigeria']
['fair', 'enough', 'anything', 'going', 'on']
['yeah', 'hopefully', 'if', 'tyler', 'can', 'do', 'it', 'could', 'maybe', 'ask', 'around', 'bit']
['don', 'know', 'how', 'stubborn', 'am', 'didn', 'even', 'want', 'to', 'go', 'to', 'the', 'hospital', 'kept', 'telling', 'mark', 'not', 'weak', 'sucker', 'hospital', 'are', 'for', 'weak', 'sucker']
['what', 'you', 'thinked', 'about', 'me', 'first', 'time', 'you', 'saw', 'me', 'in', 'class']
['gram', 'usually', 'run', 'like', 'lt', 'gt', 'half', 'eighth', 'is', 'smarter', 'though', 'and', 'get', 'you', 'almost', 'whole', 'second', 'gram', 'for', 'lt', 'gt']
['fyi', 'ha', 'ride', 'early', 'tomorrow', 'morning', 'but', 'he', 'crashing', 'at', 'our', 'place', 'tonight']
['wow', 'never', 'realized', 'that', 'you', 'were', 'so', 'embarassed', 'by', 'your', 'accomodations', 'thought', 'you', 'liked', 'it', 'since', 'wa', 'doing', 'the', 'best', 'could', 'and', 'you', 'always', 'seemed', 'so', 'happy', 'about', 'the', 'cave', 'sorry', 'didn', 'and', 'don', 'have', 'more', 'to', 'give', 'sorry', 'offered', 'sorry', 'your', 'room', 'wa', 'so', 'embarassing']
['sm', 'ac', 'sptv', 'the', 'new', 'jersey', 'devil', 'and', 'the', 'detroit', 'red', 'wing', 'play', 'ice', 'hockey', 'correct', 'or', 'incorrect', 'end', 'reply', 'end', 'sptv']
['do', 'you', 'know', 'what', 'mallika', 'sherawat', 'did', 'yesterday', 'find', 'out', 'now', 'lt', 'url', 'gt']
['congrats', 'year', 'special', 'cinema', 'pas', 'for', 'is', 'yours', 'call', 'now', 'suprman', 'matrix', 'starwars', 'etc', 'all', 'free', 'bx', 'ip', 'we', 'pm', 'dont', 'miss', 'out']
['sorry', 'll', 'call', 'later', 'in', 'meeting']
['tell', 'where', 'you', 'reached']
['yes', 'gauti', 'and', 'sehwag', 'out', 'of', 'odi', 'series']
['your', 'gonna', 'have', 'to', 'pick', 'up', 'burger', 'for', 'yourself', 'on', 'your', 'way', 'home', 'can', 'even', 'move', 'pain', 'is', 'killing', 'me']
['ha', 'ha', 'ha', 'good', 'joke', 'girl', 'are', 'situation', 'seeker']
['it', 'part', 'of', 'checking', 'iq']
['sorry', 'my', 'roommate', 'took', 'forever', 'it', 'ok', 'if', 'come', 'by', 'now']
['ok', 'lar', 'double', 'check', 'wif', 'da', 'hair', 'dresser', 'already', 'he', 'said', 'wun', 'cut', 'short', 'he', 'said', 'will', 'cut', 'until', 'look', 'nice']
['valued', 'customer', 'am', 'pleased', 'to', 'advise', 'you', 'that', 'following', 'recent', 'review', 'of', 'your', 'mob', 'no', 'you', 'are', 'awarded', 'with', 'bonus', 'prize', 'call']
['today', 'is', 'song', 'dedicated', 'day', 'which', 'song', 'will', 'dedicate', 'for', 'me', 'send', 'this', 'to', 'all', 'ur', 'valuable', 'frnds', 'but', 'first', 'rply', 'me']
['urgent', 'ur', 'awarded', 'complimentary', 'trip', 'to', 'eurodisinc', 'trav', 'aco', 'entry', 'or', 'to', 'claim', 'txt', 'dis', 'to', 'morefrmmob', 'aj']
['did', 'you', 'hear', 'about', 'the', 'new', 'divorce', 'barbie', 'it', 'come', 'with', 'all', 'of', 'ken', 'stuff']
['plane', 'to', 'give', 'on', 'this', 'month', 'end']
['wah', 'lucky', 'man', 'then', 'can', 'save', 'money', 'hee']
['finished', 'class', 'where', 'are', 'you']
['hi', 'babe', 'im', 'at', 'home', 'now', 'wanna', 'do', 'something', 'xx']
['where', 'are', 'you', 'how', 'did', 'you', 'performed']
['can', 'call', 'me', 'now']
['am', 'waiting', 'machan', 'call', 'me', 'once', 'you', 'free']
['thats', 'cool', 'am', 'gentleman', 'and', 'will', 'treat', 'you', 'with', 'dignity', 'and', 'respect']
['like', 'you', 'people', 'very', 'much', 'but', 'am', 'very', 'shy', 'pa']
['doe', 'not', 'operate', 'after', 'lt', 'gt', 'or', 'what']
['it', 'not', 'the', 'same', 'here', 'still', 'looking', 'for', 'job', 'how', 'much', 'do', 'ta', 'earn', 'there']
['sorry', 'll', 'call', 'later']
['did', 'you', 'call', 'me', 'just', 'now', 'ah']
['ok', 'am', 'on', 'the', 'way', 'to', 'home', 'hi', 'hi']
['you', 'will', 'be', 'in', 'the', 'place', 'of', 'that', 'man']
['yup', 'next', 'stop']
['call', 'you', 'later', 'don', 'have', 'network', 'if', 'urgnt', 'sm', 'me']
['for', 'real', 'when', 'getting', 'on', 'yo', 'only', 'need', 'more', 'ticket', 'and', 'one', 'more', 'jacket', 'and', 'done', 'already', 'used', 'all', 'my', 'multis']
['yes', 'started', 'to', 'send', 'request', 'to', 'make', 'it', 'but', 'pain', 'came', 'back', 'so', 'back', 'in', 'bed', 'double', 'coin', 'at', 'the', 'factory', 'too', 'gotta', 'cash', 'in', 'all', 'my', 'nitros']
['really', 'not', 'up', 'to', 'it', 'still', 'tonight', 'babe']
['ela', 'kano', 'il', 'download', 'come', 'wen', 'ur', 'free']
['yeah', 'do', 'don', 'stand', 'to', 'close', 'tho', 'you', 'll', 'catch', 'something']
['sorry', 'to', 'be', 'pain', 'is', 'it', 'ok', 'if', 'we', 'meet', 'another', 'night', 'spent', 'late', 'afternoon', 'in', 'casualty', 'and', 'that', 'mean', 'haven', 'done', 'any', 'of', 'stuff', 'moro', 'and', 'that', 'includes', 'all', 'my', 'time', 'sheet', 'and', 'that', 'sorry']
['smile', 'in', 'pleasure', 'smile', 'in', 'pain', 'smile', 'when', 'trouble', 'pours', 'like', 'rain', 'smile', 'when', 'sum', 'hurt', 'smile', 'becoz', 'someone', 'still', 'love', 'to', 'see', 'smiling']
['please', 'call', 'our', 'customer', 'service', 'representative', 'on', 'between', 'am', 'pm', 'you', 'have', 'won', 'guaranteed', 'cash', 'or', 'prize']
['havent', 'planning', 'to', 'buy', 'later', 'check', 'already', 'lido', 'only', 'got', 'show', 'in', 'afternoon', 'finish', 'work', 'already']
['your', 'free', 'ringtone', 'is', 'waiting', 'to', 'be', 'collected', 'simply', 'text', 'the', 'password', 'mix', 'to', 'to', 'verify', 'get', 'usher', 'and', 'britney', 'fml', 'po', 'box', 'mk', 'ppw']
['watching', 'telugu', 'movie', 'wat', 'abt']
['see', 'when', 'we', 'finish', 'we', 'have', 'load', 'of', 'loan', 'to', 'pay']
['hi', 'wk', 'been', 'ok', 'on', 'hols', 'now', 'yes', 'on', 'for', 'bit', 'of', 'run', 'forgot', 'that', 'have', 'hairdresser', 'appointment', 'at', 'four', 'so', 'need', 'to', 'get', 'home', 'shower', 'beforehand', 'doe', 'that', 'cause', 'prob', 'for']
['see', 'cup', 'of', 'coffee', 'animation']
['please', 'don', 'text', 'me', 'anymore', 'have', 'nothing', 'else', 'to', 'say']
['okay', 'name', 'ur', 'price', 'long', 'it', 'legal', 'wen', 'can', 'pick', 'them', 'up', 'ave', 'am', 'xx']
['still', 'looking', 'for', 'car', 'to', 'buy', 'and', 'have', 'not', 'gone', 'the', 'driving', 'test', 'yet']
['per', 'your', 'request', 'melle', 'melle', 'oru', 'minnaminunginte', 'nurungu', 'vettam', 'ha', 'been', 'set', 'your', 'callertune', 'for', 'all', 'caller', 'press', 'to', 'copy', 'your', 'friend', 'callertune']
['wow', 'you', 're', 'right', 'didn', 'mean', 'to', 'do', 'that', 'guess', 'once', 'gave', 'up', 'on', 'boston', 'men', 'and', 'changed', 'my', 'search', 'location', 'to', 'nyc', 'something', 'changed', 'cuz', 'on', 'my', 'signin', 'page', 'it', 'still', 'say', 'boston']
['umma', 'my', 'life', 'and', 'vava', 'umma', 'love', 'you', 'lot', 'dear']
['thanks', 'lot', 'for', 'your', 'wish', 'on', 'my', 'birthday', 'thanks', 'you', 'for', 'making', 'my', 'birthday', 'truly', 'memorable']
['aight', 'll', 'hit', 'you', 'up', 'when', 'get', 'some', 'cash']
['how', 'would', 'my', 'ip', 'address', 'test', 'that', 'considering', 'my', 'computer', 'isn', 'minecraft', 'server']
['know', 'grumpy', 'old', 'people', 'my', 'mom', 'wa', 'like', 'you', 'better', 'not', 'be', 'lying', 'then', 'again', 'am', 'always', 'the', 'one', 'to', 'play', 'joke']
['dont', 'worry', 'guess', 'he', 'busy']
['what', 'is', 'the', 'plural', 'of', 'the', 'noun', 'research']
['going', 'for', 'dinner', 'msg', 'you', 'after']
['ok', 'wif', 'it', 'co', 'like', 'try', 'new', 'thing', 'but', 'scared', 'dun', 'like', 'mah', 'co', 'said', 'not', 'too', 'loud']
['gent', 'we', 'are', 'trying', 'to', 'contact', 'you', 'last', 'weekend', 'draw', 'show', 'that', 'you', 'won', 'prize', 'guaranteed', 'call', 'claim', 'code', 'valid', 'hr', 'only', 'ppm']
['wa', 'ur', 'openin', 'sentence', 'very', 'formal', 'anyway', 'fine', 'too', 'juz', 'tt', 'eatin', 'too', 'much', 'puttin', 'on', 'weight', 'haha', 'so', 'anythin', 'special', 'happened']
['entered', 'my', 'cabin', 'my', 'pa', 'said', 'happy', 'day', 'bos', 'felt', 'special', 'she', 'askd', 'me', 'lunch', 'after', 'lunch', 'she', 'invited', 'me', 'to', 'her', 'apartment', 'we', 'went', 'there']
['you', 'are', 'winner', 'have', 'been', 'specially', 'selected', 'receive', 'or', 'holiday', 'flight', 'inc', 'speak', 'to', 'live', 'operator', 'claim', 'min']
['goodo', 'yes', 'we', 'must', 'speak', 'friday', 'egg', 'potato', 'ratio', 'for', 'tortilla', 'needed']
['hmm', 'my', 'uncle', 'just', 'informed', 'me', 'that', 'he', 'paying', 'the', 'school', 'directly', 'so', 'pls', 'buy', 'food']
['private', 'your', 'account', 'statement', 'for', 'show', 'unredeemed', 'bonus', 'point', 'to', 'claim', 'call', 'identifier', 'code', 'expires']
['urgent', 'your', 'mobile', 'no', 'wa', 'awarded', 'bonus', 'caller', 'prize', 'on', 'this', 'is', 'our', 'final', 'try', 'to', 'contact', 'call', 'from', 'landline', 'box', 'wr', 'ppm']
['here', 'is', 'my', 'new', 'address', 'apple', 'pair', 'all', 'that', 'malarky']
['today', 'voda', 'number', 'ending', 'are', 'selected', 'to', 'receive', 'award', 'if', 'you', 'have', 'match', 'please', 'call', 'quoting', 'claim', 'code', 'standard', 'rate', 'app']
['am', 'going', 'to', 'sao', 'mu', 'today', 'will', 'be', 'done', 'only', 'at']
['predict', 'wat', 'time', 'll', 'finish', 'buying']
['good', 'stuff', 'will', 'do']
['just', 'so', 'that', 'you', 'know', 'yetunde', 'hasn', 'sent', 'money', 'yet', 'just', 'sent', 'her', 'text', 'not', 'to', 'bother', 'sending', 'so', 'it', 'over', 'you', 'dont', 'have', 'to', 'involve', 'yourself', 'in', 'anything', 'shouldn', 'have', 'imposed', 'anything', 'on', 'you', 'in', 'the', 'first', 'place', 'so', 'for', 'that', 'apologise']
['are', 'you', 'there', 'in', 'room']
['hey', 'girl', 'how', 'hope', 'well', 'me', 'an', 'del', 'bak', 'again', 'long', 'time', 'no', 'give', 'me', 'call', 'sum', 'time', 'from', 'lucyxx']
['how', 'much', 'doe', 'it', 'cost']
['home']
['dear', 'will', 'call', 'tmorrow', 'pls', 'accomodate']
['first', 'answer', 'my', 'question']
['sunshine', 'quiz', 'wkly', 'win', 'top', 'sony', 'dvd', 'player', 'if', 'know', 'which', 'country', 'the', 'algarve', 'is', 'in', 'txt', 'ansr', 'to', 'sp', 'tyrone']
['want', 'get', 'laid', 'tonight', 'want', 'real', 'dogging', 'location', 'sent', 'direct', 'ur', 'mob', 'join', 'the', 'uk', 'largest', 'dogging', 'network', 'bt', 'txting', 'gravel', 'to', 'nt', 'ec', 'msg']
['only', 'haf', 'msn', 'it', 'yijue', 'hotmail', 'com']
['he', 'is', 'there', 'you', 'call', 'and', 'meet', 'him']
['no', 'no', 'will', 'check', 'all', 'room', 'befor', 'activity']
['you', 'll', 'not', 'rcv', 'any', 'more', 'msg', 'from', 'the', 'chat', 'svc', 'for', 'free', 'hardcore', 'service', 'text', 'go', 'to', 'if', 'get', 'nothing', 'must', 'age', 'verify', 'with', 'yr', 'network', 'try', 'again']
['got', 'lazy', 'to', 'type', 'forgot', 'in', 'lect', 'saw', 'pouch', 'but', 'like', 'not', 'nice']
['text', 'me', 'when', 'you', 're', 'on', 'the', 'way']
['sir', 'waiting', 'for', 'your', 'mail']
['swt', 'thought', 'nver', 'get', 'tired', 'of', 'doing', 'little', 'thing', 'lovable', 'person', 'coz', 'somtimes', 'those', 'little', 'thing', 'occupy', 'biggest', 'part', 'in', 'their', 'heart', 'gud', 'ni']
['know', 'you', 'are', 'can', 'you', 'pls', 'open', 'the', 'back']
['yes', 'see', 'ya', 'not', 'on', 'the', 'dot']
['whats', 'the', 'staff', 'name', 'who', 'is', 'taking', 'class', 'for']
['freemsg', 'why', 'haven', 'you', 'replied', 'to', 'my', 'text', 'randy', 'sexy', 'female', 'and', 'live', 'local', 'luv', 'to', 'hear', 'from', 'netcollex', 'ltd', 'per', 'msg', 'reply', 'stop', 'to', 'end']
['ummma', 'will', 'call', 'after', 'check', 'in', 'our', 'life', 'will', 'begin', 'from', 'qatar', 'so', 'pls', 'pray', 'very', 'hard']
['deleted', 'my', 'contact', 'that', 'why']
['sindu', 'got', 'job', 'in', 'birla', 'soft']
['the', 'wine', 'is', 'flowing', 'and', 'have', 'nevering']
['yup', 'thk', 'cine', 'is', 'better', 'co', 'no', 'need', 'go', 'down', 'plaza', 'mah']
['ok', 'ur', 'typical', 'reply']
['per', 'your', 'request', 'melle', 'melle', 'oru', 'minnaminunginte', 'nurungu', 'vettam', 'ha', 'been', 'set', 'your', 'callertune', 'for', 'all', 'caller', 'press', 'to', 'copy', 'your', 'friend', 'callertune']
['you', 'are', 'everywhere', 'dirt', 'on', 'the', 'floor', 'the', 'window', 'even', 'on', 'my', 'shirt', 'and', 'sometimes', 'when', 'open', 'my', 'mouth', 'you', 'are', 'all', 'that', 'come', 'flowing', 'out', 'dream', 'of', 'my', 'world', 'without', 'you', 'then', 'half', 'my', 'chore', 'are', 'out', 'too', 'time', 'of', 'joy', 'for', 'me', 'lot', 'of', 'tv', 'show', 'll', 'see', 'but', 'guess', 'like', 'all', 'thing', 'you', 'just', 'must', 'exist', 'like', 'rain', 'hail', 'and', 'mist', 'and', 'when', 'my', 'time', 'here', 'is', 'done', 'you', 'and', 'become', 'one']
['aaooooright', 'are', 'you', 'at', 'work']
['leaving', 'my', 'house', 'now']
['hello', 'my', 'love', 'what', 'are', 'you', 'doing', 'did', 'you', 'get', 'to', 'that', 'interview', 'today', 'are', 'you', 'you', 'happy', 'are', 'you', 'being', 'good', 'boy', 'do', 'you', 'think', 'of', 'me', 'are', 'you', 'missing', 'me']
['customer', 'service', 'annoncement', 'you', 'have', 'new', 'year', 'delivery', 'waiting', 'for', 'you', 'please', 'call', 'now', 'to', 'arrange', 'delivery']
['you', 'are', 'winner', 'have', 'been', 'specially', 'selected', 'receive', 'cash', 'or', 'holiday', 'flight', 'inc', 'speak', 'to', 'live', 'operator', 'claim']
['keep', 'yourself', 'safe', 'for', 'me', 'because', 'need', 'you', 'and', 'miss', 'you', 'already', 'and', 'envy', 'everyone', 'that', 'see', 'you', 'in', 'real', 'life']
['new', 'car', 'and', 'house', 'for', 'my', 'parent', 'have', 'only', 'new', 'job', 'in', 'hand']

In [51]:
words[0]

['go',
 'until',
 'jurong',
 'point',
 'crazy',
 'available',
 'only',
 'in',
 'bugis',
 'great',
 'world',
 'la',
 'buffet',
 'cine',
 'there',
 'got',
 'amore',
 'wat']

In [52]:
model.wv["free"].shape

(100,)

In [53]:
def avg_word2vec(corpus):
    return np.mean([model.wv[word]for word in corpus if word in model.wv.index_to_key], axis= 0)

In [54]:
from tqdm import tqdm
X=[]
for i in tqdm(range(len(words))):
    X.append(avg_word2vec(words[i]))

  0%|          | 0/5569 [00:00<?, ?it/s]/Users/sanju/PycharmProjects/NLP_basics/.venv/lib/python3.9/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/Users/sanju/PycharmProjects/NLP_basics/.venv/lib/python3.9/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
100%|██████████| 5569/5569 [00:01<00:00, 4815.54it/s]

In [55]:
len(X)

5569

In [56]:
X

[array([-0.0666744 ,  0.35209984,  0.11178985, -0.08472668,  0.17933044,
        -0.6248006 ,  0.11858006,  0.7108463 , -0.30754936, -0.19779992,
        -0.18236622, -0.33694804, -0.02976408,  0.0112215 ,  0.15763396,
        -0.2580814 , -0.14557347, -0.42699534,  0.04056635, -0.69859356,
         0.24006836,  0.07168709,  0.21644637, -0.09535784, -0.08240052,
         0.0368822 , -0.16111861, -0.3365318 , -0.29297322,  0.05148238,
         0.34289402,  0.10953797,  0.16879599, -0.02481483, -0.15753709,
         0.26876405,  0.01277766, -0.20751587, -0.12343136, -0.6424138 ,
         0.06098058, -0.25634637, -0.02031435, -0.05525959,  0.4046509 ,
        -0.15510581, -0.21943085, -0.16758314,  0.17530456,  0.32637835,
         0.14772986, -0.18911436, -0.04479935, -0.06658023, -0.11277584,
         0.18143569,  0.28812256,  0.05839568, -0.35479128,  0.11174798,
         0.1308538 ,  0.11082451, -0.17114991, -0.05918003, -0.45912167,
         0.08512647,  0.1704167 ,  0.10676063, -0.45566922,  0.35205367,
        -0.2347595 ,  0.00904225,  0.34518725, -0.2790612 ,  0.4160941 ,
         0.11638628,  0.02516776, -0.05443255, -0.37846857,  0.074623  ,
        -0.08759821, -0.09196261, -0.37535226,  0.5170997 ,  0.02568345,
        -0.01751849, -0.05124088,  0.39215773,  0.47620183,  0.09834474,
         0.33111322,  0.24473064,  0.04731962,  0.15893081,  0.46561998,
         0.3016014 ,  0.15931804, -0.33276612,  0.14676693, -0.07173704],
       dtype=float32),
 array([-0.04897078,  0.25410366,  0.076761  , -0.06398671,  0.13412026,
        -0.4466622 ,  0.08886307,  0.50240934, -0.225842  , -0.1394414 ,
        -0.12900703, -0.24467716, -0.01192146,  0.0027071 ,  0.12157296,
        -0.18357024, -0.1043885 , -0.31156537,  0.02595077, -0.5007374 ,
         0.17056963,  0.05470533,  0.1559912 , -0.06999468, -0.0550923 ,
         0.02472717, -0.11594999, -0.2470768 , -0.21227105,  0.03618893,
         0.25032705,  0.07887063,  0.12265907, -0.0190129 , -0.11442852,
         0.19886504,  0.01200809, -0.14931284, -0.09098201, -0.46968895,
         0.04118491, -0.18575153, -0.01398725, -0.04074457,  0.28844613,
        -0.11319038, -0.15430547, -0.11757652,  0.11686915,  0.23015146,
         0.10542562, -0.13746932, -0.03147371, -0.05403625, -0.07946093,
         0.12969226,  0.2049557 ,  0.04888915, -0.25176388,  0.08375142,
         0.09327038,  0.08001478, -0.12449483, -0.04500108, -0.33277142,
         0.06097457,  0.12252735,  0.0784543 , -0.33147514,  0.25205502,
        -0.1768358 ,  0.00581625,  0.24784939, -0.20576735,  0.30029893,
         0.08142936,  0.01490123, -0.04208412, -0.26804903,  0.04624462,
        -0.06368162, -0.06785242, -0.2624747 ,  0.3732252 ,  0.02183136,
        -0.00629304, -0.03056021,  0.2841764 ,  0.3464231 ,  0.07567144,
         0.23806214,  0.1751652 ,  0.0301597 ,  0.10988923,  0.33858582,
         0.21822706,  0.10900331, -0.24215193,  0.10638453, -0.05491291],
       dtype=float32),
 array([-0.06556453,  0.385714  ,  0.14403144, -0.09283958,  0.20066667,
        -0.7038586 ,  0.11658105,  0.8157523 , -0.32948726, -0.2329096 ,
        -0.2156451 , -0.40602502, -0.0226904 ,  0.03266976,  0.15619011,
        -0.26627707, -0.14425577, -0.4592889 ,  0.02219212, -0.76694286,
         0.26521885,  0.06750251,  0.19743371, -0.10187614, -0.08210315,
         0.04236778, -0.1760709 , -0.37996104, -0.32907614,  0.05246049,
         0.3964915 ,  0.12964663,  0.17553554, -0.02441142, -0.17506714,
         0.3179497 ,  0.04044041, -0.23255153, -0.11190154, -0.68985283,
         0.05974263, -0.26955143, -0.01218819, -0.08507804,  0.463484  ,
        -0.18653545, -0.2640565 , -0.19415152,  0.2318879 ,  0.39905235,
         0.17942157, -0.20750475, -0.04299293, -0.07505152, -0.10737101,
         0.2016244 ,  0.33933204,  0.08255038, -0.39202744,  0.10642944,
         0.12781942,  0.10801999, -0.18012096, -0.05943146, -0.54260606,
         0.07935334,  0.20852801,  0.10072428, -0.4736794 ,  0.40170494,
        -0.24751742, -0.02609695,  0.39533496, -0.30678537,  0.4539736 ,
         0.15428315,  0.04847138, -0.0618519 , -0.4073597 ,  0.11657323,
        -0.11241679, -0.10972204, -0.43156323,  0.5881948 ,  0.02368848,
        -0.03690832, -0.06571467,  0.46187264,  0.5439302 ,  0.09001843,
         0.3654167 ,  0.28861973,  0.07871513,  0.20197883,  0.53704745,
         0.3434647 ,  0.18774705, -0.35746995,  0.16733557, -0.09993909],
       dtype=float32),
 array([-0.08222508,  0.46540642,  0.14614318, -0.10645604,  0.24308099,
        -0.8153059 ,  0.16861854,  0.929071  , -0.41395482, -0.2556502 ,
        -0.23501937, -0.44348285, -0.03587112,  0.01105252,  0.2267855 ,
        -0.34329668, -0.19531475, -0.5725066 ,  0.05367922, -0.92876554,
         0.32219294,  0.09663371,  0.28935418, -0.11924625, -0.10674285,
         0.04733812, -0.21369816, -0.44861874, -0.38721275,  0.06916908,
         0.45264912,  0.14611882,  0.22422035, -0.03951107, -0.20945305,
         0.35393175,  0.01397243, -0.2752128 , -0.16834778, -0.85364395,
         0.07482185, -0.34934843, -0.02571372, -0.06506101,  0.5266488 ,
        -0.1997024 , -0.28503707, -0.21884044,  0.2160312 ,  0.42858955,
         0.192105  , -0.25031832, -0.05964351, -0.09255215, -0.1416847 ,
         0.23121238,  0.36722448,  0.0732742 , -0.4739183 ,  0.15639396,
         0.16668683,  0.15619747, -0.22862111, -0.08247986, -0.6095653 ,
         0.10763777,  0.22439855,  0.14967147, -0.61185724,  0.47009027,
        -0.31125602,  0.03026713,  0.4545503 , -0.37895012,  0.5579547 ,
         0.14408834,  0.03620338, -0.07392649, -0.49192724,  0.09003355,
        -0.10438552, -0.12290134, -0.4952818 ,  0.6825094 ,  0.03050122,
        -0.01323795, -0.06244859,  0.5179709 ,  0.63247395,  0.13046676,
         0.43827847,  0.31681347,  0.05694235,  0.20808303,  0.6071502 ,
         0.39634573,  0.20872562, -0.44633532,  0.19559705, -0.09847692],
       dtype=float32),
 array([-0.0666515 ,  0.3718599 ,  0.11451456, -0.09170082,  0.19604516,
        -0.65926826,  0.13169529,  0.74598354, -0.32917348, -0.20537251,
        -0.18805213, -0.35498643, -0.03106145,  0.00621727,  0.17132527,
        -0.2711039 , -0.15872394, -0.4530528 ,  0.04385298, -0.7405655 ,
         0.25439155,  0.08079192,  0.23142375, -0.0996935 , -0.08705393,
         0.04107767, -0.16710155, -0.3577591 , -0.30821037,  0.05556662,
         0.36338294,  0.11367413,  0.17672919, -0.02701862, -0.16522795,
         0.28055418,  0.01145471, -0.2196928 , -0.13271946, -0.67903376,
         0.06199039, -0.2749854 , -0.02212482, -0.05547564,  0.4244345 ,
        -0.1651313 , -0.22634894, -0.17340396,  0.17803878,  0.34183544,
         0.1552075 , -0.19841199, -0.04259963, -0.07531776, -0.12160292,
         0.19290084,  0.30300438,  0.06374878, -0.37706432,  0.12253515,
         0.14060445,  0.12212653, -0.1818098 , -0.05974911, -0.4859401 ,
         0.09328088,  0.17710021,  0.11670235, -0.48818064,  0.36805558,
        -0.25004736,  0.0188194 ,  0.3637157 , -0.29623932,  0.43870962,
         0.11970263,  0.02751742, -0.05622284, -0.39871976,  0.07285075,
        -0.08610628, -0.09659601, -0.39416817,  0.54361403,  0.02767002,
        -0.01856536, -0.04891151,  0.4146152 ,  0.5005092 ,  0.10311133,
         0.35021406,  0.26374063,  0.04696876,  0.16531655,  0.48964393,
         0.31548783,  0.1695935 , -0.35408384,  0.15616743, -0.07230315],
       dtype=float32),
 array([-0.06969266,  0.39611748,  0.12941055, -0.09325784,  0.20416366,
        -0.7014297 ,  0.13215378,  0.80668724, -0.342093  , -0.22499076,
        -0.20827338, -0.386295  , -0.02837911,  0.01873225,  0.17976372,
        -0.285312  , -0.1597302 , -0.47945386,  0.04092079, -0.7852395 ,
         0.27358216,  0.08060417,  0.23240472, -0.10615864, -0.08564632,
         0.04623399, -0.1830172 , -0.38154176, -0.32968384,  0.05536473,
         0.39110607,  0.12543121,  0.18621741, -0.02666264, -0.17809014,
         0.30693883,  0.01534898, -0.23529208, -0.13196282, -0.7230235 ,
         0.06105439, -0.28330636, -0.0204727 , -0.06533239,  0.45771936,
        -0.17679656, -0.24751459, -0.18834764,  0.20083806,  0.37733284,
         0.16991355, -0.21243888, -0.05229785, -0.08017199, -0.11834216,
         0.20466849,  0.3254633 ,  0.07273073, -0.4010373 ,  0.1242427 ,
         0.13827008,  0.124229  , -0.18946628, -0.0668807 , -0.5322525 ,
         0.09543924,  0.19532697,  0.11814858, -0.50861156,  0.40081537,
        -0.2602179 ,  0.00738408,  0.39129448, -0.3164586 ,  0.4671852 ,
         0.13392632,  0.03619845, -0.06381931, -0.4229899 ,  0.09247091,
        -0.10057908, -0.10852146, -0.42693213,  0.587823  ,  0.02668698,
        -0.02627776, -0.05417797,  0.4439652 ,  0.5376432 ,  0.1037536 ,
         0.37324914,  0.2825419 ,  0.06173297,  0.18886709,  0.5298276 ,
         0.34054172,  0.18526442, -0.370512  ,  0.16508359, -0.08479435],
       dtype=float32),
 array([-0.07963278,  0.46596947,  0.14367215, -0.11212911,  0.2444263 ,
        -0.83431244,  0.16159329,  0.95281976, -0.41114482, -0.26117268,
        -0.24416947, -0.4537407 , -0.04695163,  0.01285596,  0.21791849,
        -0.34832278, -0.1987118 , -0.5747743 ,  0.05898356, -0.93905497,
         0.323154  ,  0.09740027,  0.2903939 , -0.12391155, -0.1108843 ,
         0.05705291, -0.2208593 , -0.45054445, -0.39145324,  0.07419703,
         0.46445066,  0.14953785,  0.2228435 , -0.03347711, -0.21219508,
         0.35231656,  0.01344925, -0.27810806, -0.16849731, -0.8612513 ,
         0.07717862, -0.34335235, -0.02614036, -0.06899101,  0.535613  ,
        -0.20779325, -0.2884157 , -0.22493164,  0.22657467,  0.44031048,
         0.20077176, -0.25677106, -0.05778581, -0.09815302, -0.15155616,
         0.24262336,  0.37965187,  0.07916917, -0.4762275 ,  0.15357043,
         0.16976807,  0.15085207, -0.22635762, -0.07797676, -0.62300307,
         0.11766327,  0.23470186,  0.144645  , -0.6185632 ,  0.47269055,
        -0.30578616,  0.02282153,  0.46613535, -0.3759489 ,  0.55419457,
         0.15258257,  0.04618234, -0.07598507, -0.50222677,  0.0956691 ,
        -0.11951546, -0.12925245, -0.5055493 ,  0.6952456 ,  0.02920725,
        -0.02401615, -0.05757749,  0.52037704,  0.6298303 ,  0.12765518,
         0.44543502,  0.3247289 ,  0.06953498,  0.21071209,  0.61907053,
         0.400203  ,  0.2221804 , -0.45040566,  0.20087469, -0.09085498],
       dtype=float32),
 array([-0.03993833,  0.23719527,  0.07774884, -0.05269071,  0.13005899,
        -0.42690182,  0.07668224,  0.4899999 , -0.20943321, -0.13375907,
        -0.12648804, -0.2346277 , -0.01909653,  0.01278056,  0.11056711,
        -0.17094827, -0.09861702, -0.29023808,  0.02546202, -0.47528237,
         0.16047086,  0.04625821,  0.14209631, -0.06506627, -0.05329879,
         0.03065798, -0.10922574, -0.23078322, -0.20082152,  0.03268775,
         0.24072689,  0.07417358,  0.11447138, -0.01561934, -0.10620655,
         0.18493019,  0.0096878 , -0.13750756, -0.08183108, -0.43605724,
         0.0402959 , -0.17021805, -0.01231589, -0.03851972,  0.27590424,
        -0.10464344, -0.15201938, -0.11389579,  0.12364046,  0.23150823,
         0.10387789, -0.12902462, -0.02567204, -0.04782336, -0.07155604,
         0.12424289,  0.19709857,  0.04381517, -0.24339083,  0.07215904,
         0.08812882,  0.07222284, -0.11670452, -0.03859214, -0.32280248,
         0.05630438,  0.11914132,  0.06960936, -0.30528697,  0.24412322,
        -0.1578128 ,  0.00167526,  0.23980215, -0.18865678,  0.28111652,
         0.08119312,  0.02164168, -0.03648504, -0.2575706 ,  0.05896911,
        -0.0609023 , -0.06703556, -0.25749725,  0.35475928,  0.01798792,
        -0.01786381, -0.03231584,  0.27030194,  0.3240556 ,  0.06215903,
         0.22479427,  0.16839439,  0.03754516,  0.11782477,  0.3193113 ,
         0.20600995,  0.11264586, -0.22786117,  0.10095908, -0.05046182],
       dtype=float32),
 array([-0.06382552,  0.37455562,  0.16658887, -0.07733497,  0.19795905,
        -0.7012657 ,  0.10390126,  0.82728267, -0.31771052, -0.24748899,
        -0.20564397, -0.4180122 , -0.03059921,  0.0384724 ,  0.13432212,
        -0.2573429 , -0.15388845, -0.46073952,  0.01780515, -0.7563948 ,
         0.23915367,  0.05845686,  0.18959178, -0.10167172, -0.08607931,
         0.05177046, -0.189177  , -0.37423328, -0.33113614,  0.06059612,
         0.40801194,  0.11770153,  0.18748564, -0.03096235, -0.17513676,
         0.33313477,  0.05658423, -0.23260266, -0.11421529, -0.6814441 ,
         0.05587441, -0.25987583, -0.01256983, -0.09715666,  0.4634463 ,
        -0.17951512, -0.26459542, -0.19261691,  0.25473493,  0.40221184,
         0.18142524, -0.20713237, -0.04252811, -0.07052154, -0.10732588,
         0.21011378,  0.34211293,  0.07611036, -0.39229918,  0.08315511,
         0.14259222,  0.10688743, -0.17755242, -0.03805777, -0.53634   ,
         0.06968935,  0.22714692,  0.0972725 , -0.46842432,  0.41447765,
        -0.24535121, -0.03338475,  0.39766356, -0.28895628,  0.45246595,
         0.171056  ,  0.03024578, -0.07790712, -0.4127844 ,  0.11816222,
        -0.12712684, -0.10096073, -0.4424329 ,  0.5785858 ,  0.00937653,
        -0.03916633, -0.05864144,  0.46269152,  0.5317362 ,  0.08918246,
         0.36846095,  0.30275008,  0.08665383,  0.21294206,  0.542718  ,
         0.35450318,  0.19039848, -0.37236568,  0.16883318, -0.0957173 ],
       dtype=float32),
 array([-0.09552033,  0.5741406 ,  0.23199977, -0.12936498,  0.29381067,
        -1.0531379 ,  0.16305459,  1.2393082 , -0.48258895, -0.3600451 ,
        -0.31882414, -0.61902994, -0.04144697,  0.06279495,  0.22850396,
        -0.38405755, -0.20558457, -0.66915804,  0.02836447, -1.1419786 ,
         0.39726204,  0.08070205,  0.26561853, -0.15532967, -0.11286806,
         0.05847995, -0.26596457, -0.56535226, -0.4971638 ,  0.07383783,
         0.60406697,  0.19042873,  0.26894727, -0.0469063 , -0.2689694 ,
         0.5006718 ,  0.09035862, -0.3330001 , -0.15633236, -1.0100267 ,
         0.08446771, -0.3825341 , -0.02268109, -0.14137147,  0.70340663,
        -0.28095782, -0.40659294, -0.29066688,  0.37274352,  0.6257478 ,
         0.27909422, -0.31647897, -0.06833068, -0.1128682 , -0.14588425,
         0.299567  ,  0.5232879 ,  0.13667616, -0.5777841 ,  0.12875135,
         0.18913664,  0.14556865, -0.26861814, -0.07777447, -0.82166666,
         0.11296419,  0.32396582,  0.14641182, -0.6865694 ,  0.6021119 ,
        -0.36710313, -0.05967654,  0.59714586, -0.44730896,  0.6782823 ,
         0.24729773,  0.0801271 , -0.10208372, -0.6014935 ,  0.20238574,
        -0.18248339, -0.1723057 , -0.6710773 ,  0.8865288 ,  0.03297168,
        -0.07968969, -0.10942928,  0.70504236,  0.8207218 ,  0.11750918,
         0.54184574,  0.43827727,  0.12614013,  0.3095115 ,  0.8290145 ,
         0.53505826,  0.28153208, -0.5271113 ,  0.2437898 , -0.16282955],
       dtype=float32),
 array([-0.08040123,  0.4560469 ,  0.14019588, -0.10808238,  0.23765707,
        -0.81972057,  0.15828781,  0.933335  , -0.4042906 , -0.25732338,
        -0.23660417, -0.44047037, -0.03928642,  0.01384983,  0.21041374,
        -0.33910906, -0.18969151, -0.5597476 ,  0.0536132 , -0.9100795 ,
         0.31750613,  0.09163364,  0.2793112 , -0.12506847, -0.10781445,
         0.05288958, -0.21797732, -0.44235444, -0.3827422 ,  0.06538475,
         0.45797324,  0.14631984,  0.21565041, -0.03737704, -0.2029511 ,
         0.3501473 ,  0.01611227, -0.26772824, -0.15991254, -0.8438492 ,
         0.07491188, -0.34006318, -0.0223108 , -0.0662729 ,  0.52463484,
        -0.20352574, -0.28584275, -0.21486735,  0.22963706,  0.4325431 ,
         0.19514196, -0.25059634, -0.05792322, -0.09267925, -0.14276502,
         0.23595223,  0.37572402,  0.07718629, -0.46674222,  0.14962883,
         0.16901387,  0.15128238, -0.22337434, -0.07643032, -0.6085199 ,
         0.11424296,  0.22735433,  0.14083669, -0.6020285 ,  0.462007  ,
        -0.307757  ,  0.01361254,  0.45609045, -0.36754498,  0.54920304,
         0.15267423,  0.03817772, -0.06762358, -0.49636126,  0.09725947,
        -0.1125767 , -0.12640485, -0.49604297,  0.6801076 ,  0.03155535,
        -0.022322  , -0.06048302,  0.51518893,  0.6221607 ,  0.12642007,
         0.437586  ,  0.32138246,  0.0671566 ,  0.21101204,  0.60999656,
         0.39311343,  0.20965847, -0.43640718,  0.18969722, -0.09562077],
       dtype=float32),
 array([-0.07954092,  0.49455887,  0.17491932, -0.11568271,  0.26070586,
        -0.8960166 ,  0.1522202 ,  1.0358278 , -0.42670813, -0.29206315,
        -0.27360854, -0.507882  , -0.03335433,  0.03095946,  0.21067989,
        -0.34903717, -0.19409466, -0.5950749 ,  0.03514755, -0.9884945 ,
         0.33986083,  0.09231871,  0.26891926, -0.13374047, -0.11006737,
         0.05925466, -0.22568706, -0.48360002, -0.42159015,  0.07461067,
         0.50035995,  0.15917821,  0.23174746, -0.03523207, -0.2246033 ,
         0.39767554,  0.04345638, -0.29137722, -0.15609346, -0.8918261 ,
         0.07979698, -0.34956762, -0.01928679, -0.09687457,  0.58799225,
        -0.22835283, -0.3330012 , -0.24932785,  0.28327027,  0.4983828 ,
         0.22273333, -0.27259716, -0.05600195, -0.09910577, -0.14603667,
         0.2653939 ,  0.4242659 ,  0.09970865, -0.5004205 ,  0.1457905 ,
         0.17791072,  0.14626299, -0.2383189 , -0.0739883 , -0.680639  ,
         0.10660299,  0.25544938,  0.13750383, -0.61986005,  0.5098153 ,
        -0.31956804, -0.01832358,  0.505322  , -0.39208806,  0.5818644 ,
         0.18532583,  0.05706403, -0.07634874, -0.5278327 ,  0.13551149,
        -0.14087898, -0.13625596, -0.5510336 ,  0.7420541 ,  0.03069533,
        -0.04317171, -0.07460301,  0.58146966,  0.68483037,  0.1158161 ,
         0.47090247,  0.3619121 ,  0.09009173,  0.2563745 ,  0.67729783,
         0.4343157 ,  0.23572564, -0.46587515,  0.21063778, -0.11966967],
       dtype=float32),
 array([-0.07003705,  0.40765622,  0.17115489, -0.09449992,  0.21287286,
        -0.75245416,  0.11415646,  0.8827423 , -0.34332293, -0.2594467 ,
        -0.2299844 , -0.44300866, -0.02799229,  0.04401878,  0.14961411,
        -0.27390262, -0.15635319, -0.49051693,  0.0190466 , -0.8152462 ,
         0.27147117,  0.06352871,  0.19811146, -0.10646014, -0.0854753 ,
         0.04604555, -0.19298252, -0.405892  , -0.35296616,  0.05593624,
         0.4285933 ,  0.13599941,  0.18998148, -0.02384842, -0.18630052,
         0.35281777,  0.05584064, -0.2503634 , -0.1146841 , -0.7301345 ,
         0.06108833, -0.27634102, -0.01236986, -0.10024627,  0.4985051 ,
        -0.1968139 , -0.2892044 , -0.20898081,  0.26398677,  0.4349402 ,
         0.19853605, -0.22129005, -0.04811392, -0.07536184, -0.11263548,
         0.22301106,  0.3718783 ,  0.09144061, -0.41753647,  0.10135385,
         0.1417587 ,  0.11222363, -0.19076873, -0.05567928, -0.5864997 ,
         0.07469688,  0.2345334 ,  0.10424249, -0.4938415 ,  0.43502623,
        -0.26204816, -0.03644642,  0.42809045, -0.3206403 ,  0.48452073,
         0.17434224,  0.04385958, -0.07267687, -0.44189167,  0.1343582 ,
        -0.13044158, -0.1157771 , -0.47141048,  0.6309497 ,  0.01413539,
        -0.0463222 , -0.07298594,  0.5036429 ,  0.5812452 ,  0.08844234,
         0.39151633,  0.3197783 ,  0.09000407,  0.2267463 ,  0.5860093 ,
         0.3731859 ,  0.20477477, -0.38042548,  0.18076745, -0.1106329 ],
       dtype=float32),
 array([-0.06225613,  0.36321154,  0.11456399, -0.08923284,  0.19156629,
        -0.647025  ,  0.12001439,  0.7384241 , -0.31838784, -0.20401476,
        -0.19305862, -0.35073313, -0.02976372,  0.0163952 ,  0.16818172,
        -0.26077548, -0.1486519 , -0.4416325 ,  0.0392171 , -0.72205305,
         0.24812603,  0.07692957,  0.22255015, -0.09840076, -0.07986331,
         0.04727976, -0.16381462, -0.3514682 , -0.3038949 ,  0.05493218,
         0.3567296 ,  0.11157084,  0.17297365, -0.02347226, -0.16518527,
         0.28157756,  0.01324002, -0.21201383, -0.12753756, -0.66221505,
         0.05847031, -0.26165286, -0.01808733, -0.05569002,  0.4155405 ,

In [57]:
X_new  = np.array(X,dtype=object)

In [58]:
X_new[0].shape

(100,)

In [59]:
y = df[list(map(lambda x : len(x)>0,corpus))]

In [60]:
y = pd.get_dummies(y['class'])

In [61]:
y = y.iloc[:,0].values

In [62]:
y.shape

(5569,)

In [63]:
final_df = pd.DataFrame()
for i in tqdm(range(0,len(X))):
    final_df = final_df._append(pd.DataFrame(X[i].reshape(1,-1)), ignore_index=True)

  0%|          | 0/5569 [00:00<?, ?it/s]/var/folders/1j/7qsmcprn49bbt7vp46fzmpx80000gn/T/ipykernel_62825/3101955966.py:3: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = final_df._append(pd.DataFrame(X[i].reshape(1,-1)), ignore_index=True)
100%|██████████| 5569/5569 [00:00<00:00, 7599.18it/s]

In [64]:
final_df["Output"] = y

In [65]:
final_df.dropna(axis=0,inplace=True)

In [66]:
final_df.head()

,0,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,Output
0,-0.066674,0.352100,0.111790,-0.084727,0.179330,-0.624801,0.118580,0.710846,-0.307549,-0.197800,...,0.244731,0.047320,0.158931,0.465620,0.301601,0.159318,-0.332766,0.146767,-0.071737,True
1,-0.048971,0.254104,0.076761,-0.063987,0.134120,-0.446662,0.088863,0.502409,-0.225842,-0.139441,...,0.175165,0.030160,0.109889,0.338586,0.218227,0.109003,-0.242152,0.106385,-0.054913,True
2,-0.065565,0.385714,0.144031,-0.092840,0.200667,-0.703859,0.116581,0.815752,-0.329487,-0.232910,...,0.288620,0.078715,0.201979,0.537047,0.343465,0.187747,-0.357470,0.167336,-0.099939,False
3,-0.082225,0.465406,0.146143,-0.106456,0.243081,-0.815306,0.168619,0.929071,-0.413955,-0.255650,...,0.316813,0.056942,0.208083,0.607150,0.396346,0.208726,-0.446335,0.195597,-0.098477,True
4,-0.066652,0.371860,0.114515,-0.091701,0.196045,-0.659268,0.131695,0.745984,-0.329173,-0.205373,...,0.263741,0.046969,0.165317,0.489644,0.315488,0.169593,-0.354084,0.156167,-0.072303,True

In [67]:
y = final_df["Output"]
X = final_df.drop("Output",axis=1).values

In [68]:
len(X)

5544

In [69]:
X = X.reshape(X.shape[0], 1, X.shape[1])

In [70]:
len(y)

5544

In [71]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [72]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.layers import Input

In [73]:
y = y.map({'spam':"False", 'ham':"True"})

In [74]:
timesteps = X_train.shape[1]  # Extract timesteps from the shape
features = X_train.shape[2] 
model = Sequential()
model.add(Input(shape=(timesteps, features)))  # Define input shape explicitly
model.add(LSTM(units=128, return_sequences=True))  # Add LSTM layer with return_sequences=True
model.add(LSTM(units=128))  # Add another LSTM layer
model.add(Dense(1, activation='sigmoid'))
optimizer = Adam(learning_rate=0.1)
model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy'])

In [75]:
model.fit(X_train, y_train, epochs=10, batch_size=32)

Epoch 1/10
139/139 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8216 - loss: 0.4335
Epoch 2/10
139/139 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9000 - loss: 0.2689
Epoch 3/10
139/139 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9246 - loss: 0.1832
Epoch 4/10
139/139 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9359 - loss: 0.1691
Epoch 5/10
139/139 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9412 - loss: 0.1525
Epoch 6/10
139/139 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9206 - loss: 0.2138
Epoch 7/10
139/139 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9344 - loss: 0.1912
Epoch 8/10
139/139 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9273 - loss: 0.2191
Epoch 9/10
139/139 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8756 - loss: 0.3361
Epoch 10/10
139/139 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9213 - loss: 0.2285

In [76]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_2 (LSTM)                   │ (None, 1, 128)         │       117,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_3 (LSTM)                   │ (None, 128)            │       131,584 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │           129 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 746,885 (2.85 MB)

 Trainable params: 248,961 (972.50 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 497,924 (1.90 MB)

In [77]:
from sklearn.metrics import accuracy_score,f1_score
y_pred = model.predict(X_test)
y_pred_classes = (y_pred > 0.5).astype(int)  # Convert probabilities to class labels (0 or 1)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred_classes)
f1 = f1_score(y_test, y_pred_classes)
print(f"Accuracy: {accuracy}")
print(f"F1 Score: {f1}")

35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
Accuracy: 0.8764652840396754
F1 Score: 0.9341662662181643

In [78]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(Input(shape=(timesteps, features)))
model.add(Dense(64, activation='relu') ) # Input layer (100 dimensions)
model.add(Dense(32, activation='relu'))                     # Hidden layer
model.add(Dense(2, activation='softmax'))                    # Output layer (2 classes: spam/ham)

model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [79]:
model.fit(X_train, y_train, epochs=10, batch_size=32)

Epoch 1/10
139/139 ━━━━━━━━━━━━━━━━━━━━ 1s 530us/step - accuracy: 0.8033 - loss: 0.4811
Epoch 2/10
139/139 ━━━━━━━━━━━━━━━━━━━━ 0s 534us/step - accuracy: 0.8574 - loss: 0.3242
Epoch 3/10
139/139 ━━━━━━━━━━━━━━━━━━━━ 0s 570us/step - accuracy: 0.9160 - loss: 0.2030
Epoch 4/10
139/139 ━━━━━━━━━━━━━━━━━━━━ 0s 536us/step - accuracy: 0.9284 - loss: 0.1752
Epoch 5/10
139/139 ━━━━━━━━━━━━━━━━━━━━ 0s 572us/step - accuracy: 0.9430 - loss: 0.1551
Epoch 6/10
139/139 ━━━━━━━━━━━━━━━━━━━━ 0s 523us/step - accuracy: 0.9401 - loss: 0.1583
Epoch 7/10
139/139 ━━━━━━━━━━━━━━━━━━━━ 0s 538us/step - accuracy: 0.9436 - loss: 0.1497
Epoch 8/10
139/139 ━━━━━━━━━━━━━━━━━━━━ 0s 530us/step - accuracy: 0.9484 - loss: 0.1404
Epoch 9/10
139/139 ━━━━━━━━━━━━━━━━━━━━ 0s 542us/step - accuracy: 0.9526 - loss: 0.1394
Epoch 10/10
139/139 ━━━━━━━━━━━━━━━━━━━━ 0s 546us/step - accuracy: 0.9495 - loss: 0.1327

In [80]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 1, 64)          │         6,464 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1, 32)          │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1, 2)           │            66 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 25,832 (100.91 KB)

 Trainable params: 8,610 (33.63 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 17,222 (67.28 KB)

In [81]:
loss, accuracy = model.evaluate(X_test, y_test)
print("Test Accuracy:", accuracy) 
print("Test Loss:", loss)

35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 410us/step - accuracy: 0.9140 - loss: 0.2118
Test Accuracy: 0.917944073677063
Test Loss: 0.20491136610507965

In [82]:
y_pred = model.predict(X_test)
predicted_class = y_pred.argmax(axis=-1)

35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 619us/step

In [83]:
f1 = f1_score(y_test,predicted_class)

In [84]:
f1

0.9516214779372674

In [85]:
predicted_class

array([[0],
       [1],
       [1],
       ...,
       [1],
       [1],
       [1]])